import { db, patientsTable, medicationsTable, visitsTable, labResultsTable, alertsTable, consentTable } from "@workspace/db";

async function seed() {
  console.log("Seeding Sanad database with demo patients...");

  const patients = await db.insert(patientsTable).values([
    {
      nationalId: "1000000001",
      fullName: "Mohammed Al-Qahtani",
      dateOfBirth: "1965-03-15",
      gender: "male",
      bloodType: "O+",
      phone: "+966501234567",
      emergencyContact: "Fatima Al-Qahtani",
      emergencyPhone: "+966501234568",
      chronicConditions: ["Hypertension", "Type 2 Diabetes", "Coronary Artery Disease"],
      allergies: ["Penicillin", "Sulfa drugs"],
      riskScore: 65,
    },
    {
      nationalId: "1000000002",
      fullName: "Fatima Al-Zahrani",
      dateOfBirth: "1978-07-22",
      gender: "female",
      bloodType: "A+",
      phone: "+966502345678",
      emergencyContact: "Ahmad Al-Zahrani",
      emergencyPhone: "+966502345679",
      chronicConditions: ["Hypothyroidism", "Asthma"],
      allergies: ["Aspirin", "Latex"],
      riskScore: 35,
    },
    {
      nationalId: "1000000003",
      fullName: "Khalid Al-Rashidi",
      dateOfBirth: "1955-11-08",
      gender: "male",
      bloodType: "B+",
      phone: "+966503456789",
      emergencyContact: "Nora Al-Rashidi",
      emergencyPhone: "+966503456790",
      chronicConditions: ["Heart Failure", "Chronic Kidney Disease", "Hypertension", "Atrial Fibrillation"],
      allergies: ["Iodine contrast", "Aspirin", "Codeine"],
      riskScore: 88,
    },
    {
      nationalId: "1000000004",
      fullName: "Nora Al-Shehri",
      dateOfBirth: "1990-04-17",
      gender: "female",
      bloodType: "AB+",
      phone: "+966504567890",
      emergencyContact: "Saad Al-Shehri",
      emergencyPhone: "+966504567891",
      chronicConditions: [],
      allergies: [],
      riskScore: 8,
    },
    {
      nationalId: "1000000005",
      fullName: "Abdullah Al-Dosari",
      dateOfBirth: "1945-09-03",
      gender: "male",
      bloodType: "A-",
      phone: "+966505678901",
      emergencyContact: "Hessa Al-Dosari",
      emergencyPhone: "+966505678902",
      chronicConditions: ["COPD", "Type 2 Diabetes", "Hypertension", "Chronic Kidney Disease"],
      allergies: ["Penicillin", "Ibuprofen", "NSAIDs"],
      riskScore: 92,
    },
    {
      nationalId: "1000000006",
      fullName: "Sara Al-Ghamdi",
      dateOfBirth: "1985-12-25",
      gender: "female",
      bloodType: "O-",
      phone: "+966506789012",
      emergencyContact: "Omar Al-Ghamdi",
      emergencyPhone: "+966506789013",
      chronicConditions: ["Depression", "Migraine"],
      allergies: ["Tramadol"],
      riskScore: 22,
    },
    {
      nationalId: "1000000007",
      fullName: "Abdulaziz Al-Mutairi",
      dateOfBirth: "1970-06-12",
      gender: "male",
      bloodType: "B-",
      phone: "+966507890123",
      emergencyContact: "Maha Al-Mutairi",
      emergencyPhone: "+966507890124",
      chronicConditions: ["Hypertension", "Hypercholesterolemia"],
      allergies: ["Amoxicillin"],
      riskScore: 30,
    },
    {
      nationalId: "1000000008",
      fullName: "Hessa Al-Otaibi",
      dateOfBirth: "1958-02-28",
      gender: "female",
      bloodType: "O+",
      phone: "+966508901234",
      emergencyContact: "Bandar Al-Otaibi",
      emergencyPhone: "+966508901235",
      chronicConditions: ["Rheumatoid Arthritis", "Osteoporosis", "Hypertension"],
      allergies: ["Gold compounds", "Methotrexate rash"],
      riskScore: 55,
    },
    {
      nationalId: "1000000009",
      fullName: "Omar Al-Harbi",
      dateOfBirth: "1995-08-14",
      gender: "male",
      bloodType: "A+",
      phone: "+966509012345",
      emergencyContact: "Layla Al-Harbi",
      emergencyPhone: "+966509012346",
      chronicConditions: [],
      allergies: ["Bee stings", "Peanuts"],
      riskScore: 12,
    },
    {
      nationalId: "1000000010",
      fullName: "Maryam Al-Anzi",
      dateOfBirth: "1962-05-30",
      gender: "female",
      bloodType: "AB-",
      phone: "+966510123456",
      emergencyContact: "Faisal Al-Anzi",
      emergencyPhone: "+966510123457",
      chronicConditions: ["Type 1 Diabetes", "Hypertension", "Hypothyroidism", "Chronic Kidney Disease"],
      allergies: ["Sulfa drugs", "Cephalosporins"],
      riskScore: 78,
    },
    { nationalId: "1000000011", fullName: "Bandar Al-Sulami", dateOfBirth: "1972-01-20", gender: "male", bloodType: "O+", phone: "+966511234567", emergencyContact: "Rima Al-Sulami", emergencyPhone: "+966511234568", chronicConditions: ["Hypertension"], allergies: [], riskScore: 15 },
    { nationalId: "1000000012", fullName: "Rima Al-Jaber", dateOfBirth: "1980-09-05", gender: "female", bloodType: "A+", phone: "+966512345678", emergencyContact: "Khalid Al-Jaber", emergencyPhone: "+966512345679", chronicConditions: ["Hyperthyroidism", "Anxiety"], allergies: ["Iodine"], riskScore: 28 },
    { nationalId: "1000000013", fullName: "Faisal Al-Ahmadi", dateOfBirth: "1948-04-11", gender: "male", bloodType: "B+", phone: "+966513456789", emergencyContact: "Dalal Al-Ahmadi", emergencyPhone: "+966513456790", chronicConditions: ["Coronary Artery Disease", "Hypertension", "Type 2 Diabetes", "Stroke"], allergies: ["Aspirin", "Warfarin alternatives"], riskScore: 85 },
    { nationalId: "1000000014", fullName: "Dalal Al-Yami", dateOfBirth: "1993-11-17", gender: "female", bloodType: "O+", phone: "+966514567890", emergencyContact: "Sami Al-Yami", emergencyPhone: "+966514567891", chronicConditions: [], allergies: [], riskScore: 5 },
    { nationalId: "1000000015", fullName: "Sami Al-Bishi", dateOfBirth: "1967-07-09", gender: "male", bloodType: "A+", phone: "+966515678901", emergencyContact: "Nada Al-Bishi", emergencyPhone: "+966515678902", chronicConditions: ["COPD", "Hypertension"], allergies: ["Penicillin"], riskScore: 42 },
    { nationalId: "1000000016", fullName: "Nada Al-Qahtani", dateOfBirth: "1975-03-28", gender: "female", bloodType: "B+", phone: "+966516789012", emergencyContact: "Tariq Al-Qahtani", emergencyPhone: "+966516789013", chronicConditions: ["Lupus", "Depression"], allergies: ["Sulfa drugs", "NSAIDs"], riskScore: 50 },
    { nationalId: "1000000017", fullName: "Tariq Al-Zahrani", dateOfBirth: "1989-06-14", gender: "male", bloodType: "AB+", phone: "+966517890123", emergencyContact: "Ghada Al-Zahrani", emergencyPhone: "+966517890124", chronicConditions: [], allergies: [], riskScore: 6 },
    { nationalId: "1000000018", fullName: "Ghada Al-Rashidi", dateOfBirth: "1952-10-03", gender: "female", bloodType: "O-", phone: "+966518901234", emergencyContact: "Majed Al-Rashidi", emergencyPhone: "+966518901235", chronicConditions: ["Hypertension", "Osteoporosis", "Type 2 Diabetes"], allergies: ["Penicillin"], riskScore: 60 },
    { nationalId: "1000000019", fullName: "Majed Al-Shehri", dateOfBirth: "1983-02-19", gender: "male", bloodType: "A-", phone: "+966519012345", emergencyContact: "Reema Al-Shehri", emergencyPhone: "+966519012346", chronicConditions: ["Hypertension"], allergies: [], riskScore: 18 },
    { nationalId: "1000000020", fullName: "Reema Al-Dosari", dateOfBirth: "1997-08-07", gender: "female", bloodType: "O+", phone: "+966520123456", emergencyContact: "Walid Al-Dosari", emergencyPhone: "+966520123457", chronicConditions: [], allergies: ["Latex"], riskScore: 4 },
    { nationalId: "1000000021", fullName: "Walid Al-Ghamdi", dateOfBirth: "1960-05-25", gender: "male", bloodType: "B-", phone: "+966521234567", emergencyContact: "Hana Al-Ghamdi", emergencyPhone: "+966521234568", chronicConditions: ["Hypertension", "Hypercholesterolemia", "Atrial Fibrillation"], allergies: ["Ibuprofen"], riskScore: 55 },
    { nationalId: "1000000022", fullName: "Hana Al-Mutairi", dateOfBirth: "1987-12-12", gender: "female", bloodType: "A+", phone: "+966522345678", emergencyContact: "Yousef Al-Mutairi", emergencyPhone: "+966522345679", chronicConditions: ["Polycystic Ovary Syndrome"], allergies: [], riskScore: 14 },
    { nationalId: "1000000023", fullName: "Yousef Al-Otaibi", dateOfBirth: "1943-08-30", gender: "male", bloodType: "O+", phone: "+966523456789", emergencyContact: "Mona Al-Otaibi", emergencyPhone: "+966523456790", chronicConditions: ["Heart Failure", "COPD", "Type 2 Diabetes", "Hypertension"], allergies: ["Aspirin", "Penicillin", "Iodine"], riskScore: 95 },
    { nationalId: "1000000024", fullName: "Mona Al-Harbi", dateOfBirth: "1991-04-04", gender: "female", bloodType: "AB+", phone: "+966524567890", emergencyContact: "Rayan Al-Harbi", emergencyPhone: "+966524567891", chronicConditions: ["Asthma"], allergies: ["Aspirin"], riskScore: 20 },
    { nationalId: "1000000025", fullName: "Rayan Al-Anzi", dateOfBirth: "1976-09-18", gender: "male", bloodType: "B+", phone: "+966525678901", emergencyContact: "Lina Al-Anzi", emergencyPhone: "+966525678902", chronicConditions: ["Hypertension", "Type 2 Diabetes"], allergies: [], riskScore: 32 },
    { nationalId: "1000000026", fullName: "Lina Al-Sulami", dateOfBirth: "1969-01-07", gender: "female", bloodType: "A+", phone: "+966526789012", emergencyContact: "Hamad Al-Sulami", emergencyPhone: "+966526789013", chronicConditions: ["Rheumatoid Arthritis", "Hypertension"], allergies: ["Gold compounds"], riskScore: 45 },
    { nationalId: "1000000027", fullName: "Hamad Al-Jaber", dateOfBirth: "1984-06-22", gender: "male", bloodType: "O+", phone: "+966527890123", emergencyContact: "Shahad Al-Jaber", emergencyPhone: "+966527890124", chronicConditions: [], allergies: [], riskScore: 7 },
    { nationalId: "1000000028", fullName: "Shahad Al-Ahmadi", dateOfBirth: "1999-11-30", gender: "female", bloodType: "O-", phone: "+966528901234", emergencyContact: "Hasan Al-Ahmadi", emergencyPhone: "+966528901235", chronicConditions: [], allergies: ["Penicillin"], riskScore: 10 },
    { nationalId: "1000000029", fullName: "Hasan Al-Yami", dateOfBirth: "1958-07-15", gender: "male", bloodType: "A+", phone: "+966529012345", emergencyContact: "Wedad Al-Yami", emergencyPhone: "+966529012346", chronicConditions: ["Coronary Artery Disease", "Hypertension", "Type 2 Diabetes"], allergies: ["Sulfa drugs"], riskScore: 72 },
    { nationalId: "1000000030", fullName: "Wedad Al-Bishi", dateOfBirth: "1973-03-10", gender: "female", bloodType: "B+", phone: "+966530123456", emergencyContact: "Jaber Al-Bishi", emergencyPhone: "+966530123457", chronicConditions: ["Hypothyroidism", "Hypertension"], allergies: [], riskScore: 28 },
    { nationalId: "1000000031", fullName: "Jaber Al-Qahtani", dateOfBirth: "1950-09-01", gender: "male", bloodType: "AB-", phone: "+966531234567", emergencyContact: "Thuraya Al-Qahtani", emergencyPhone: "+966531234568", chronicConditions: ["Chronic Kidney Disease", "Hypertension", "Anemia"], allergies: ["Ibuprofen", "NSAIDs"], riskScore: 68 },
    { nationalId: "1000000032", fullName: "Thuraya Al-Zahrani", dateOfBirth: "1988-12-06", gender: "female", bloodType: "O+", phone: "+966532345678", emergencyContact: "Nawaf Al-Zahrani", emergencyPhone: "+966532345679", chronicConditions: ["Depression", "Anxiety"], allergies: ["Tramadol"], riskScore: 25 },
    { nationalId: "1000000033", fullName: "Nawaf Al-Rashidi", dateOfBirth: "1963-05-20", gender: "male", bloodType: "A+", phone: "+966533456789", emergencyContact: "Hind Al-Rashidi", emergencyPhone: "+966533456790", chronicConditions: ["Hypertension", "Hypercholesterolemia", "Hypertension"], allergies: [], riskScore: 38 },
    { nationalId: "1000000034", fullName: "Hind Al-Shehri", dateOfBirth: "1994-02-14", gender: "female", bloodType: "B-", phone: "+966534567890", emergencyContact: "Turki Al-Shehri", emergencyPhone: "+966534567891", chronicConditions: [], allergies: [], riskScore: 5 },
    { nationalId: "1000000035", fullName: "Turki Al-Dosari", dateOfBirth: "1947-08-28", gender: "male", bloodType: "O+", phone: "+966535678901", emergencyContact: "Zainab Al-Dosari", emergencyPhone: "+966535678902", chronicConditions: ["COPD", "Heart Failure", "Hypertension"], allergies: ["Aspirin", "Codeine"], riskScore: 80 },
    { nationalId: "1000000036", fullName: "Zainab Al-Ghamdi", dateOfBirth: "1981-04-09", gender: "female", bloodType: "A+", phone: "+966536789012", emergencyContact: "Mishaal Al-Ghamdi", emergencyPhone: "+966536789013", chronicConditions: ["Type 2 Diabetes"], allergies: [], riskScore: 22 },
    { nationalId: "1000000037", fullName: "Mishaal Al-Mutairi", dateOfBirth: "1956-10-17", gender: "male", bloodType: "B+", phone: "+966537890123", emergencyContact: "Rana Al-Mutairi", emergencyPhone: "+966537890124", chronicConditions: ["Stroke", "Hypertension", "Atrial Fibrillation", "Type 2 Diabetes"], allergies: ["Warfarin (prior bleed)"], riskScore: 82 },
    { nationalId: "1000000038", fullName: "Rana Al-Otaibi", dateOfBirth: "1986-07-03", gender: "female", bloodType: "O+", phone: "+966538901234", emergencyContact: "Sultan Al-Otaibi", emergencyPhone: "+966538901235", chronicConditions: ["Asthma", "Allergic Rhinitis"], allergies: ["Aspirin", "Beta-blockers"], riskScore: 20 },
    { nationalId: "1000000039", fullName: "Sultan Al-Harbi", dateOfBirth: "1977-01-25", gender: "male", bloodType: "A-", phone: "+966539012345", emergencyContact: "Jawaher Al-Harbi", emergencyPhone: "+966539012346", chronicConditions: ["Hypertension", "Type 2 Diabetes", "Hypercholesterolemia"], allergies: ["Penicillin"], riskScore: 42 },
    { nationalId: "1000000040", fullName: "Jawaher Al-Anzi", dateOfBirth: "1993-09-11", gender: "female", bloodType: "AB+", phone: "+966540123456", emergencyContact: "Badr Al-Anzi", emergencyPhone: "+966540123457", chronicConditions: [], allergies: [], riskScore: 6 },
    { nationalId: "1000000041", fullName: "Badr Al-Sulami", dateOfBirth: "1961-03-05", gender: "male", bloodType: "O+", phone: "+966541234567", emergencyContact: "Maha Al-Sulami", emergencyPhone: "+966541234568", chronicConditions: ["Hypertension", "Coronary Artery Disease"], allergies: ["Aspirin"], riskScore: 50 },
    { nationalId: "1000000042", fullName: "Maha Al-Jaber", dateOfBirth: "1979-11-22", gender: "female", bloodType: "B+", phone: "+966542345678", emergencyContact: "Nasser Al-Jaber", emergencyPhone: "+966542345679", chronicConditions: ["Hypothyroidism", "Depression"], allergies: [], riskScore: 25 },
    { nationalId: "1000000043", fullName: "Nasser Al-Ahmadi", dateOfBirth: "1953-06-18", gender: "male", bloodType: "A+", phone: "+966543456789", emergencyContact: "Fatima Al-Ahmadi", emergencyPhone: "+966543456790", chronicConditions: ["Heart Failure", "Chronic Kidney Disease", "Type 2 Diabetes", "Hypertension", "Anemia"], allergies: ["Penicillin", "Sulfa drugs", "NSAIDs"], riskScore: 96 },
    { nationalId: "1000000044", fullName: "Aisha Al-Yami", dateOfBirth: "1996-04-30", gender: "female", bloodType: "O-", phone: "+966544567890", emergencyContact: "Majid Al-Yami", emergencyPhone: "+966544567891", chronicConditions: [], allergies: [], riskScore: 4 },
    { nationalId: "1000000045", fullName: "Majid Al-Bishi", dateOfBirth: "1968-12-14", gender: "male", bloodType: "AB+", phone: "+966545678901", emergencyContact: "Najwa Al-Bishi", emergencyPhone: "+966545678902", chronicConditions: ["Hypertension", "COPD"], allergies: ["Ibuprofen"], riskScore: 40 },
    { nationalId: "1000000046", fullName: "Najwa Al-Qahtani", dateOfBirth: "1982-08-26", gender: "female", bloodType: "A+", phone: "+966546789012", emergencyContact: "Essam Al-Qahtani", emergencyPhone: "+966546789013", chronicConditions: ["Polycystic Ovary Syndrome", "Hypothyroidism"], allergies: [], riskScore: 20 },
    { nationalId: "1000000047", fullName: "Essam Al-Zahrani", dateOfBirth: "1959-02-08", gender: "male", bloodType: "B+", phone: "+966547890123", emergencyContact: "Marwa Al-Zahrani", emergencyPhone: "+966547890124", chronicConditions: ["Type 2 Diabetes", "Hypertension", "Coronary Artery Disease"], allergies: ["Aspirin"], riskScore: 70 },
    { nationalId: "1000000048", fullName: "Marwa Al-Rashidi", dateOfBirth: "1991-10-15", gender: "female", bloodType: "O+", phone: "+966548901234", emergencyContact: "Khalil Al-Rashidi", emergencyPhone: "+966548901235", chronicConditions: ["Asthma"], allergies: [], riskScore: 15 },
    { nationalId: "1000000049", fullName: "Khalil Al-Shehri", dateOfBirth: "1974-06-01", gender: "male", bloodType: "A-", phone: "+966549012345", emergencyContact: "Lamya Al-Shehri", emergencyPhone: "+966549012346", chronicConditions: ["Hypertension", "Type 2 Diabetes"], allergies: ["Penicillin"], riskScore: 35 },
    { nationalId: "1000000050", fullName: "Lamya Al-Dosari", dateOfBirth: "2000-03-22", gender: "female", bloodType: "O+", phone: "+966550123456", emergencyContact: "Farid Al-Dosari", emergencyPhone: "+966550123457", chronicConditions: [], allergies: [], riskScore: 3 },
  ]).returning();

  console.log(`Inserted ${patients.length} patients`);

  const patientIds = patients.map(p => p.id);

  const medications = await db.insert(medicationsTable).values([
    { patientId: patientIds[0]!, drugName: "Metformin", dosage: "1000mg", frequency: "Twice daily", prescribedBy: "Dr. Khalid Al-Rashid", hospital: "King Fahad Medical City", startDate: "2023-01-15", isActive: true },
    { patientId: patientIds[0]!, drugName: "Atorvastatin", dosage: "40mg", frequency: "Once daily at night", prescribedBy: "Dr. Khalid Al-Rashid", hospital: "King Fahad Medical City", startDate: "2023-01-15", isActive: true },
    { patientId: patientIds[0]!, drugName: "Amlodipine", dosage: "10mg", frequency: "Once daily", prescribedBy: "Dr. Reem Al-Saud", hospital: "King Faisal Specialist Hospital", startDate: "2022-06-01", isActive: true },
    { patientId: patientIds[0]!, drugName: "Aspirin", dosage: "100mg", frequency: "Once daily", prescribedBy: "Dr. Reem Al-Saud", hospital: "King Faisal Specialist Hospital", startDate: "2022-06-01", isActive: true },
    { patientId: patientIds[0]!, drugName: "Lisinopril", dosage: "10mg", frequency: "Once daily", prescribedBy: "Dr. Reem Al-Saud", hospital: "King Faisal Specialist Hospital", startDate: "2023-03-10", isActive: true },
    { patientId: patientIds[1]!, drugName: "Levothyroxine", dosage: "100mcg", frequency: "Once daily morning fasting", prescribedBy: "Dr. Samia Al-Qahtani", hospital: "Prince Sultan Medical City", startDate: "2021-09-01", isActive: true },
    { patientId: patientIds[1]!, drugName: "Salbutamol Inhaler", dosage: "100mcg/dose", frequency: "As needed", prescribedBy: "Dr. Samia Al-Qahtani", hospital: "Prince Sultan Medical City", startDate: "2020-03-15", isActive: true },
    { patientId: patientIds[2]!, drugName: "Warfarin", dosage: "5mg", frequency: "Once daily", prescribedBy: "Dr. Hassan Al-Otaibi", hospital: "King Khalid University Hospital", startDate: "2022-08-20", isActive: true },
    { patientId: patientIds[2]!, drugName: "Furosemide", dosage: "40mg", frequency: "Once daily", prescribedBy: "Dr. Hassan Al-Otaibi", hospital: "King Khalid University Hospital", startDate: "2022-08-20", isActive: true },
    { patientId: patientIds[2]!, drugName: "Carvedilol", dosage: "12.5mg", frequency: "Twice daily", prescribedBy: "Dr. Hassan Al-Otaibi", hospital: "King Khalid University Hospital", startDate: "2022-08-20", isActive: true },
    { patientId: patientIds[2]!, drugName: "Amiodarone", dosage: "200mg", frequency: "Once daily", prescribedBy: "Dr. Tariq Al-Ghamdi", hospital: "Riyadh Military Hospital", startDate: "2023-02-14", isActive: true },
    { patientId: patientIds[4]!, drugName: "Insulin Glargine", dosage: "20 units", frequency: "Once daily at bedtime", prescribedBy: "Dr. Basma Al-Sulami", hospital: "King Abdulaziz Medical City", startDate: "2020-11-01", isActive: true },
    { patientId: patientIds[4]!, drugName: "Tiotropium Inhaler", dosage: "18mcg", frequency: "Once daily", prescribedBy: "Dr. Basma Al-Sulami", hospital: "King Abdulaziz Medical City", startDate: "2021-04-15", isActive: true },
    { patientId: patientIds[4]!, drugName: "Amlodipine", dosage: "5mg", frequency: "Once daily", prescribedBy: "Dr. Basma Al-Sulami", hospital: "King Abdulaziz Medical City", startDate: "2020-11-01", isActive: true },
    { patientId: patientIds[5]!, drugName: "Fluoxetine", dosage: "20mg", frequency: "Once daily", prescribedBy: "Dr. Joud Al-Jaber", hospital: "National Guard Hospital", startDate: "2023-05-10", isActive: true },
    { patientId: patientIds[5]!, drugName: "Propranolol", dosage: "40mg", frequency: "As needed for migraine", prescribedBy: "Dr. Joud Al-Jaber", hospital: "National Guard Hospital", startDate: "2023-05-10", isActive: true },
    { patientId: patientIds[9]!, drugName: "Insulin Aspart", dosage: "8 units", frequency: "Three times daily with meals", prescribedBy: "Dr. Nadia Al-Harbi", hospital: "Prince Salman Hospital", startDate: "2019-06-01", isActive: true },
    { patientId: patientIds[9]!, drugName: "Levothyroxine", dosage: "75mcg", frequency: "Once daily morning fasting", prescribedBy: "Dr. Nadia Al-Harbi", hospital: "Prince Salman Hospital", startDate: "2020-01-15", isActive: true },
    { patientId: patientIds[9]!, drugName: "Ramipril", dosage: "5mg", frequency: "Once daily", prescribedBy: "Dr. Nadia Al-Harbi", hospital: "Prince Salman Hospital", startDate: "2021-03-20", isActive: true },
    { patientId: patientIds[9]!, drugName: "Furosemide", dosage: "20mg", frequency: "Once daily", prescribedBy: "Dr. Nadia Al-Harbi", hospital: "Prince Salman Hospital", startDate: "2022-07-10", isActive: true },
    { patientId: patientIds[6]!, drugName: "Amlodipine", dosage: "5mg", frequency: "Once daily", prescribedBy: "Dr. Walid Al-Anzi", hospital: "Al-Moosa Specialist Hospital", startDate: "2022-02-01", isActive: true },
    { patientId: patientIds[6]!, drugName: "Simvastatin", dosage: "40mg", frequency: "Once daily at night", prescribedBy: "Dr. Walid Al-Anzi", hospital: "Al-Moosa Specialist Hospital", startDate: "2022-02-01", isActive: true },
  ]).returning();

  console.log(`Inserted ${medications.length} medications`);

  const visits = await db.insert(visitsTable).values([
    { patientId: patientIds[0]!, visitDate: "2026-03-01", hospital: "King Fahad Medical City", department: "Endocrinology", doctor: "Dr. Khalid Al-Rashid", diagnosis: "Type 2 Diabetes - routine follow-up. HbA1c 7.8% - fair control.", visitType: "outpatient", notes: "Increased metformin dose. Reinforced dietary counseling." },
    { patientId: patientIds[0]!, visitDate: "2026-01-15", hospital: "King Faisal Specialist Hospital", department: "Cardiology", doctor: "Dr. Reem Al-Saud", diagnosis: "Coronary Artery Disease - stable angina. Nuclear stress test scheduled.", visitType: "outpatient" },
    { patientId: patientIds[0]!, visitDate: "2025-11-20", hospital: "King Fahad Medical City", department: "Emergency", doctor: "Dr. Turki Al-Dosari", diagnosis: "Hypertensive urgency — BP 190/110. Managed with IV labetalol and discharged.", visitType: "emergency" },
    { patientId: patientIds[0]!, visitDate: "2025-08-10", hospital: "King Fahad Medical City", department: "Endocrinology", doctor: "Dr. Khalid Al-Rashid", diagnosis: "Type 2 Diabetes annual review. HbA1c 8.2%.", visitType: "outpatient" },
    { patientId: patientIds[1]!, visitDate: "2026-02-20", hospital: "Prince Sultan Medical City", department: "Endocrinology", doctor: "Dr. Samia Al-Qahtani", diagnosis: "Hypothyroidism — TSH within range. Continue current dose.", visitType: "follow-up" },
    { patientId: patientIds[1]!, visitDate: "2025-09-05", hospital: "Prince Sultan Medical City", department: "Pulmonology", doctor: "Dr. Ahmad Al-Ghamdi", diagnosis: "Asthma — mild persistent. Good control on current inhaler.", visitType: "outpatient" },
    { patientId: patientIds[2]!, visitDate: "2026-03-10", hospital: "King Khalid University Hospital", department: "Cardiology", doctor: "Dr. Hassan Al-Otaibi", diagnosis: "Heart Failure — NYHA Class II. INR 2.4, well within range. Echo shows EF 35%.", visitType: "follow-up" },
    { patientId: patientIds[2]!, visitDate: "2026-01-28", hospital: "Riyadh Military Hospital", department: "Cardiology", doctor: "Dr. Tariq Al-Ghamdi", diagnosis: "Atrial Fibrillation — rate controlled. Amiodarone therapy continued.", visitType: "outpatient" },
    { patientId: patientIds[2]!, visitDate: "2025-12-15", hospital: "King Khalid University Hospital", department: "Emergency", doctor: "Dr. Layla Al-Harbi", diagnosis: "Acute decompensated heart failure. IV furosemide 80mg. Admitted 3 days.", visitType: "emergency" },
    { patientId: patientIds[2]!, visitDate: "2025-10-07", hospital: "King Khalid University Hospital", department: "Nephrology", doctor: "Dr. Saad Al-Bishi", diagnosis: "CKD Stage 3 — eGFR 42. Monitoring renal function.", visitType: "outpatient" },
    { patientId: patientIds[4]!, visitDate: "2026-02-28", hospital: "King Abdulaziz Medical City", department: "Pulmonology", doctor: "Dr. Basma Al-Sulami", diagnosis: "COPD exacerbation — moderate. Started oral prednisolone and azithromycin.", visitType: "inpatient" },
    { patientId: patientIds[4]!, visitDate: "2025-11-10", hospital: "King Abdulaziz Medical City", department: "Endocrinology", doctor: "Dr. Fahad Al-Jaber", diagnosis: "Type 2 Diabetes — HbA1c 9.1%. Poor control. Insulin adjusted.", visitType: "outpatient" },
    { patientId: patientIds[9]!, visitDate: "2026-03-05", hospital: "Prince Salman Hospital", department: "Endocrinology", doctor: "Dr. Nadia Al-Harbi", diagnosis: "Type 1 Diabetes — HbA1c 7.2%. Good control. CGM data reviewed.", visitType: "follow-up" },
    { patientId: patientIds[9]!, visitDate: "2025-12-20", hospital: "Prince Salman Hospital", department: "Nephrology", doctor: "Dr. Yusuf Al-Anzi", diagnosis: "CKD Stage 2 — eGFR 68. Annual nephrology review.", visitType: "outpatient" },
    { patientId: patientIds[5]!, visitDate: "2026-02-14", hospital: "National Guard Hospital", department: "Psychiatry", doctor: "Dr. Joud Al-Jaber", diagnosis: "Depression — responding to fluoxetine. Continue current dose.", visitType: "follow-up" },
    { patientId: patientIds[12]!, visitDate: "2026-03-08", hospital: "King Abdulaziz Hospital", department: "Emergency", doctor: "Dr. Omar Al-Sulami", diagnosis: "Acute coronary syndrome — NSTEMI. Admitted to CCU. PCI performed.", visitType: "emergency" },
    { patientId: patientIds[12]!, visitDate: "2026-01-20", hospital: "King Abdulaziz Hospital", department: "Cardiology", doctor: "Dr. Walid Al-Zahrani", diagnosis: "Post-stroke follow-up. Mild residual left weakness. Physical therapy ongoing.", visitType: "follow-up" },
    { patientId: patientIds[22]!, visitDate: "2026-03-12", hospital: "National Guard Hospital", department: "Emergency", doctor: "Dr. Rima Al-Rashidi", diagnosis: "Acute pulmonary edema secondary to decompensated heart failure. Intubated briefly.", visitType: "emergency" },
    { patientId: patientIds[42]!, visitDate: "2026-03-15", hospital: "King Faisal Specialist Hospital", department: "Emergency", doctor: "Dr. Khalid Al-Mutairi", diagnosis: "Hypertensive emergency — BP 230/140. IV nitroprusside. ICU admission.", visitType: "emergency" },
    { patientId: patientIds[3]!, visitDate: "2026-02-10", hospital: "Prince Sultan Medical City", department: "General Practice", doctor: "Dr. Ahmad Al-Yami", diagnosis: "Annual wellness check. All parameters normal.", visitType: "outpatient" },
  ]).returning();

  console.log(`Inserted ${visits.length} visits`);

  const labResults = await db.insert(labResultsTable).values([
    { patientId: patientIds[0]!, testName: "HbA1c", testDate: "2026-03-01", result: "7.8", unit: "%", referenceRange: "< 7.0", status: "abnormal", hospital: "King Fahad Medical City", notes: "Fair control. Target < 7.0%" },
    { patientId: patientIds[0]!, testName: "Fasting Blood Glucose", testDate: "2026-03-01", result: "138", unit: "mg/dL", referenceRange: "70-100", status: "abnormal", hospital: "King Fahad Medical City" },
    { patientId: patientIds[0]!, testName: "LDL Cholesterol", testDate: "2026-01-15", result: "2.1", unit: "mmol/L", referenceRange: "< 1.8", status: "abnormal", hospital: "King Faisal Specialist Hospital" },
    { patientId: patientIds[0]!, testName: "Creatinine", testDate: "2026-01-15", result: "88", unit: "umol/L", referenceRange: "62-106", status: "normal", hospital: "King Faisal Specialist Hospital" },
    { patientId: patientIds[0]!, testName: "eGFR", testDate: "2026-01-15", result: "72", unit: "mL/min/1.73m²", referenceRange: "> 60", status: "normal", hospital: "King Faisal Specialist Hospital" },
    { patientId: patientIds[1]!, testName: "TSH", testDate: "2026-02-20", result: "3.2", unit: "mIU/L", referenceRange: "0.4-4.0", status: "normal", hospital: "Prince Sultan Medical City" },
    { patientId: patientIds[1]!, testName: "Free T4", testDate: "2026-02-20", result: "15.8", unit: "pmol/L", referenceRange: "12-22", status: "normal", hospital: "Prince Sultan Medical City" },
    { patientId: patientIds[2]!, testName: "INR", testDate: "2026-03-10", result: "2.4", unit: "", referenceRange: "2.0-3.0", status: "normal", hospital: "King Khalid University Hospital", notes: "Warfarin therapy - within therapeutic range" },
    { patientId: patientIds[2]!, testName: "Creatinine", testDate: "2026-03-10", result: "168", unit: "umol/L", referenceRange: "62-106", status: "abnormal", hospital: "King Khalid University Hospital", notes: "CKD - stable, monitoring" },
    { patientId: patientIds[2]!, testName: "BNP", testDate: "2026-03-10", result: "890", unit: "pg/mL", referenceRange: "< 100", status: "critical", hospital: "King Khalid University Hospital", notes: "Elevated consistent with decompensated heart failure" },
    { patientId: patientIds[2]!, testName: "Potassium", testDate: "2026-03-10", result: "5.6", unit: "mmol/L", referenceRange: "3.5-5.0", status: "critical", hospital: "King Khalid University Hospital", notes: "Hyperkalemia - ACE inhibitor + CKD" },
    { patientId: patientIds[4]!, testName: "HbA1c", testDate: "2026-02-28", result: "9.1", unit: "%", referenceRange: "< 7.0", status: "critical", hospital: "King Abdulaziz Medical City", notes: "Very poor glycemic control" },
    { patientId: patientIds[4]!, testName: "Creatinine", testDate: "2026-02-28", result: "198", unit: "umol/L", referenceRange: "62-106", status: "abnormal", hospital: "King Abdulaziz Medical City" },
    { patientId: patientIds[4]!, testName: "SpO2", testDate: "2026-02-28", result: "88", unit: "%", referenceRange: "> 95", status: "critical", hospital: "King Abdulaziz Medical City", notes: "COPD exacerbation" },
    { patientId: patientIds[9]!, testName: "HbA1c", testDate: "2026-03-05", result: "7.2", unit: "%", referenceRange: "< 7.5 (T1DM)", status: "normal", hospital: "Prince Salman Hospital", notes: "Good control for Type 1 DM" },
    { patientId: patientIds[9]!, testName: "eGFR", testDate: "2026-03-05", result: "68", unit: "mL/min/1.73m²", referenceRange: "> 60", status: "normal", hospital: "Prince Salman Hospital" },
    { patientId: patientIds[9]!, testName: "Urinary Microalbumin", testDate: "2026-03-05", result: "38", unit: "mg/g", referenceRange: "< 30", status: "abnormal", hospital: "Prince Salman Hospital", notes: "Early nephropathy detected" },
    { patientId: patientIds[12]!, testName: "Troponin I", testDate: "2026-03-08", result: "4.8", unit: "ng/mL", referenceRange: "< 0.04", status: "critical", hospital: "King Abdulaziz Hospital", notes: "NSTEMI - elevated troponin" },
    { patientId: patientIds[22]!, testName: "BNP", testDate: "2026-03-12", result: "2340", unit: "pg/mL", referenceRange: "< 100", status: "critical", hospital: "National Guard Hospital", notes: "Acute decompensated HF" },
    { patientId: patientIds[42]!, testName: "Creatinine", testDate: "2026-03-15", result: "310", unit: "umol/L", referenceRange: "62-106", status: "critical", hospital: "King Faisal Specialist Hospital", notes: "Hypertensive emergency - acute kidney injury" },
  ]).returning();

  console.log(`Inserted ${labResults.length} lab results`);

  const alerts = await db.insert(alertsTable).values([
    { patientId: patientIds[2]!, alertType: "drug-interaction", severity: "critical", title: "CRITICAL: Warfarin + Amiodarone Interaction", message: "Amiodarone significantly potentiates warfarin anticoagulation (INR can rise 30-50%). Life-threatening bleeding risk. Reduce warfarin dose immediately.", isRead: false },
    { patientId: patientIds[2]!, alertType: "critical-lab", severity: "critical", title: "Critical Potassium Level: 5.6 mmol/L", message: "Hyperkalemia detected (K+ 5.6 mmol/L). ACE inhibitor + CKD combination. Risk of life-threatening cardiac arrhythmia.", isRead: false },
    { patientId: patientIds[2]!, alertType: "critical-lab", severity: "critical", title: "Critical BNP: 890 pg/mL", message: "BNP markedly elevated at 890 pg/mL indicating acute decompensated heart failure. Urgent cardiology review required.", isRead: false },
    { patientId: patientIds[4]!, alertType: "critical-lab", severity: "critical", title: "Critical HbA1c: 9.1%", message: "Very poor glycemic control (HbA1c 9.1%). Immediate insulin dose adjustment required. High risk of complications.", isRead: false },
    { patientId: patientIds[4]!, alertType: "critical-lab", severity: "critical", title: "Critical SpO2: 88%", message: "Oxygen saturation critically low at 88% during COPD exacerbation. Supplemental oxygen required.", isRead: false },
    { patientId: patientIds[0]!, alertType: "predictive", severity: "moderate", title: "Predictive Alert: Cardiovascular Risk", message: "AI analysis: Patient has 3 major cardiovascular risk factors (hypertension, diabetes, CAD). 5-year MACE risk elevated. Consider cardiology referral.", isRead: false },
    { patientId: patientIds[0]!, alertType: "risk-score", severity: "high", title: "High Risk Score: 65/100", message: "Patient risk score 65 — classified as HIGH RISK. Multiple chronic conditions and polypharmacy noted. Care coordinator assessment recommended.", isRead: true },
    { patientId: patientIds[9]!, alertType: "predictive", severity: "moderate", title: "Early Diabetic Nephropathy Detected", message: "Microalbuminuria 38 mg/g detected. Possible early-stage nephropathy. Tighten blood pressure control and review ACE inhibitor dose.", isRead: false },
    { patientId: patientIds[12]!, alertType: "critical-lab", severity: "critical", title: "Critical Troponin: 4.8 ng/mL", message: "Markedly elevated Troponin I (4.8 ng/mL) — NSTEMI confirmed. Patient admitted to CCU. Immediate cardiology intervention required.", isRead: true },
    { patientId: patientIds[22]!, alertType: "critical-lab", severity: "critical", title: "Critical BNP: 2340 pg/mL", message: "Severely elevated BNP (2340 pg/mL) indicating acute decompensated heart failure. Patient intubated. ICU level care.", isRead: true },
    { patientId: patientIds[42]!, alertType: "critical-lab", severity: "critical", title: "Acute Kidney Injury: Creatinine 310 umol/L", message: "Creatinine 310 umol/L during hypertensive emergency. Acute kidney injury suspected. Nephrology consultation urgent.", isRead: false },
    { patientId: patientIds[6]!, alertType: "drug-interaction", severity: "moderate", title: "Drug Interaction: Amiodarone + Simvastatin", message: "Amiodarone inhibits simvastatin metabolism via CYP3A4. Limit simvastatin to 20mg/day to prevent myopathy risk.", isRead: false },
  ]).returning();

  console.log(`Inserted ${alerts.length} alerts`);

  // Seed default consent records for first 3 demo patients
  const consentRecords = [];
  for (let i = 0; i < Math.min(3, patientIds.length); i++) {
    const pid = patientIds[i]!;
    consentRecords.push(
      { patientId: pid, consentType: "data_sharing",    purpose: "Allow SANAD Clinical Network to access medical records", grantedTo: "SANAD Clinical Network",    granted: true,  notes: "Default consent on registration" },
      { patientId: pid, consentType: "emergency_access",purpose: "Allow SRCA emergency access during medical emergency",    grantedTo: "SRCA Emergency Services",   granted: true,  notes: "Default consent on registration" },
      { patientId: pid, consentType: "insurance",       purpose: "Allow Tawuniya Insurance to access records for claims",   grantedTo: "Tawuniya Insurance",        granted: true,  notes: "Default consent on registration" },
      { patientId: pid, consentType: "ai_processing",   purpose: "Required: AI engines process data for risk scoring",      grantedTo: "SANAD AI Division",         granted: true,  notes: "Platform requirement" },
      { patientId: pid, consentType: "research",        purpose: "Anonymous data for national health research",             grantedTo: "SANAD Research Division",   granted: false, notes: "Opt-in — not enabled by default" },
      { patientId: pid, consentType: "family_linking",  purpose: "Link health record to family for genetic risk analysis",  grantedTo: "SANAD Family Health Module",granted: false, notes: "Opt-in — not enabled by default" },
    );
  }
  const consents = await db.insert(consentTable).values(consentRecords).returning();
  console.log(`Inserted ${consents.length} consent records`);

  console.log("Seed complete! Database populated with 50 patients, medications, visits, lab results, alerts, and consent records.");
}

seed().catch(console.error).finally(() => process.exit(0));
